// +build !ignore_autogenerated

/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was autogenerated by defaulter-gen. Do not edit it manually!

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// RegisterDefaults adds defaulters functions to the given scheme.
// Public to allow building arbitrary schemes.
// All generated defaulters are covering - they call all nested defaulters.
func RegisterDefaults(scheme *runtime.Scheme) error {
	scheme.AddTypeDefaultingFunc(&ClusterRole{}, func(obj interface{}) { SetObjectDefaults_ClusterRole(obj.(*ClusterRole)) })
	scheme.AddTypeDefaultingFunc(&ClusterRoleBinding{}, func(obj interface{}) { SetObjectDefaults_ClusterRoleBinding(obj.(*ClusterRoleBinding)) })
	scheme.AddTypeDefaultingFunc(&ClusterRoleBindingList{}, func(obj interface{}) { SetObjectDefaults_ClusterRoleBindingList(obj.(*ClusterRoleBindingList)) })
	scheme.AddTypeDefaultingFunc(&ClusterRoleList{}, func(obj interface{}) { SetObjectDefaults_ClusterRoleList(obj.(*ClusterRoleList)) })
	scheme.AddTypeDefaultingFunc(&Role{}, func(obj interface{}) { SetObjectDefaults_Role(obj.(*Role)) })
	scheme.AddTypeDefaultingFunc(&RoleBinding{}, func(obj interface{}) { SetObjectDefaults_RoleBinding(obj.(*RoleBinding)) })
	scheme.AddTypeDefaultingFunc(&RoleBindingList{}, func(obj interface{}) { SetObjectDefaults_RoleBindingList(obj.(*RoleBindingList)) })
	scheme.AddTypeDefaultingFunc(&RoleList{}, func(obj interface{}) { SetObjectDefaults_RoleList(obj.(*RoleList)) })
	return nil
}

func SetObjectDefaults_ClusterRole(in *ClusterRole) {
	if in.ObjectMeta.CreationTimestamp.Time.loc != nil {
		for i := range in.ObjectMeta.CreationTimestamp.Time.loc.zone {
			a := &in.ObjectMeta.CreationTimestamp.Time.loc.zone[i]
		}
		for i := range in.ObjectMeta.CreationTimestamp.Time.loc.tx {
			a := &in.ObjectMeta.CreationTimestamp.Time.loc.tx[i]
		}
		if in.ObjectMeta.CreationTimestamp.Time.loc.cacheZone != nil {
		}
	}
	if in.ObjectMeta.DeletionTimestamp != nil {
	}
	if in.ObjectMeta.DeletionGracePeriodSeconds != nil {
	}
	for i := range in.ObjectMeta.OwnerReferences {
		a := &in.ObjectMeta.OwnerReferences[i]
		if a.Controller != nil {
		}
	}
	if in.ObjectMeta.Initializers != nil {
		for i := range in.ObjectMeta.Initializers.Pending {
			a := &in.ObjectMeta.Initializers.Pending[i]
		}
		if in.ObjectMeta.Initializers.Result != nil {
			if in.ObjectMeta.Initializers.Result.Details != nil {
				for i := range in.ObjectMeta.Initializers.Result.Details.Causes {
					a := &in.ObjectMeta.Initializers.Result.Details.Causes[i]
				}
			}
		}
	}
	for i := range in.ObjectMeta.Finalizers {
		a := &in.ObjectMeta.Finalizers[i]
	}
	for i := range in.Rules {
		a := &in.Rules[i]
	}
}

func SetObjectDefaults_ClusterRoleBinding(in *ClusterRoleBinding) {
	SetDefaults_ClusterRoleBinding(in)
	if in.ObjectMeta.CreationTimestamp.Time.loc != nil {
		for i := range in.ObjectMeta.CreationTimestamp.Time.loc.zone {
			a := &in.ObjectMeta.CreationTimestamp.Time.loc.zone[i]
		}
		for i := range in.ObjectMeta.CreationTimestamp.Time.loc.tx {
			a := &in.ObjectMeta.CreationTimestamp.Time.loc.tx[i]
		}
		if in.ObjectMeta.CreationTimestamp.Time.loc.cacheZone != nil {
		}
	}
	if in.ObjectMeta.DeletionTimestamp != nil {
	}
	if in.ObjectMeta.DeletionGracePeriodSeconds != nil {
	}
	for i := range in.ObjectMeta.OwnerReferences {
		a := &in.ObjectMeta.OwnerReferences[i]
		if a.Controller != nil {
		}
	}
	if in.ObjectMeta.Initializers != nil {
		for i := range in.ObjectMeta.Initializers.Pending {
			a := &in.ObjectMeta.Initializers.Pending[i]
		}
		if in.ObjectMeta.Initializers.Result != nil {
			if in.ObjectMeta.Initializers.Result.Details != nil {
				for i := range in.ObjectMeta.Initializers.Result.Details.Causes {
					a := &in.ObjectMeta.Initializers.Result.Details.Causes[i]
				}
			}
		}
	}
	for i := range in.ObjectMeta.Finalizers {
		a := &in.ObjectMeta.Finalizers[i]
	}
	for i := range in.Subjects {
		a := &in.Subjects[i]
		SetDefaults_Subject(a)
	}
}

func SetObjectDefaults_ClusterRoleBindingList(in *ClusterRoleBindingList) {
	for i := range in.Items {
		a := &in.Items[i]
		SetObjectDefaults_ClusterRoleBinding(a)
	}
}

func SetObjectDefaults_ClusterRoleList(in *ClusterRoleList) {
	for i := range in.Items {
		a := &in.Items[i]
		SetObjectDefaults_ClusterRole(a)
	}
}

func SetObjectDefaults_Role(in *Role) {
	if in.ObjectMeta.CreationTimestamp.Time.loc != nil {
		for i := range in.ObjectMeta.CreationTimestamp.Time.loc.zone {
			a := &in.ObjectMeta.CreationTimestamp.Time.loc.zone[i]
		}
		for i := range in.ObjectMeta.CreationTimestamp.Time.loc.tx {
			a := &in.ObjectMeta.CreationTimestamp.Time.loc.tx[i]
		}
		if in.ObjectMeta.CreationTimestamp.Time.loc.cacheZone != nil {
		}
	}
	if in.ObjectMeta.DeletionTimestamp != nil {
	}
	if in.ObjectMeta.DeletionGracePeriodSeconds != nil {
	}
	for i := range in.ObjectMeta.OwnerReferences {
		a := &in.ObjectMeta.OwnerReferences[i]
		if a.Controller != nil {
		}
	}
	if in.ObjectMeta.Initializers != nil {
		for i := range in.ObjectMeta.Initializers.Pending {
			a := &in.ObjectMeta.Initializers.Pending[i]
		}
		if in.ObjectMeta.Initializers.Result != nil {
			if in.ObjectMeta.Initializers.Result.Details != nil {
				for i := range in.ObjectMeta.Initializers.Result.Details.Causes {
					a := &in.ObjectMeta.Initializers.Result.Details.Causes[i]
				}
			}
		}
	}
	for i := range in.ObjectMeta.Finalizers {
		a := &in.ObjectMeta.Finalizers[i]
	}
	for i := range in.Rules {
		a := &in.Rules[i]
	}
}

func SetObjectDefaults_RoleBinding(in *RoleBinding) {
	SetDefaults_RoleBinding(in)
	if in.ObjectMeta.CreationTimestamp.Time.loc != nil {
		for i := range in.ObjectMeta.CreationTimestamp.Time.loc.zone {
			a := &in.ObjectMeta.CreationTimestamp.Time.loc.zone[i]
		}
		for i := range in.ObjectMeta.CreationTimestamp.Time.loc.tx {
			a := &in.ObjectMeta.CreationTimestamp.Time.loc.tx[i]
		}
		if in.ObjectMeta.CreationTimestamp.Time.loc.cacheZone != nil {
		}
	}
	if in.ObjectMeta.DeletionTimestamp != nil {
	}
	if in.ObjectMeta.DeletionGracePeriodSeconds != nil {
	}
	for i := range in.ObjectMeta.OwnerReferences {
		a := &in.ObjectMeta.OwnerReferences[i]
		if a.Controller != nil {
		}
	}
	if in.ObjectMeta.Initializers != nil {
		for i := range in.ObjectMeta.Initializers.Pending {
			a := &in.ObjectMeta.Initializers.Pending[i]
		}
		if in.ObjectMeta.Initializers.Result != nil {
			if in.ObjectMeta.Initializers.Result.Details != nil {
				for i := range in.ObjectMeta.Initializers.Result.Details.Causes {
					a := &in.ObjectMeta.Initializers.Result.Details.Causes[i]
				}
			}
		}
	}
	for i := range in.ObjectMeta.Finalizers {
		a := &in.ObjectMeta.Finalizers[i]
	}
	for i := range in.Subjects {
		a := &in.Subjects[i]
		SetDefaults_Subject(a)
	}
}

func SetObjectDefaults_RoleBindingList(in *RoleBindingList) {
	for i := range in.Items {
		a := &in.Items[i]
		SetObjectDefaults_RoleBinding(a)
	}
}

func SetObjectDefaults_RoleList(in *RoleList) {
	for i := range in.Items {
		a := &in.Items[i]
		SetObjectDefaults_Role(a)
	}
}
