// +build !ignore_autogenerated

/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was autogenerated by defaulter-gen. Do not edit it manually!

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
	api_v1 "k8s.io/kubernetes/pkg/api/v1"
)

// RegisterDefaults adds defaulters functions to the given scheme.
// Public to allow building arbitrary schemes.
// All generated defaulters are covering - they call all nested defaulters.
func RegisterDefaults(scheme *runtime.Scheme) error {
	scheme.AddTypeDefaultingFunc(&Job{}, func(obj interface{}) { SetObjectDefaults_Job(obj.(*Job)) })
	scheme.AddTypeDefaultingFunc(&JobList{}, func(obj interface{}) { SetObjectDefaults_JobList(obj.(*JobList)) })
	return nil
}

func SetObjectDefaults_Job(in *Job) {
	SetDefaults_Job(in)
	if in.ObjectMeta.CreationTimestamp.Time.loc != nil {
		for i := range in.ObjectMeta.CreationTimestamp.Time.loc.zone {
			a := &in.ObjectMeta.CreationTimestamp.Time.loc.zone[i]
		}
		for i := range in.ObjectMeta.CreationTimestamp.Time.loc.tx {
			a := &in.ObjectMeta.CreationTimestamp.Time.loc.tx[i]
		}
		if in.ObjectMeta.CreationTimestamp.Time.loc.cacheZone != nil {
		}
	}
	if in.ObjectMeta.DeletionTimestamp != nil {
	}
	if in.ObjectMeta.DeletionGracePeriodSeconds != nil {
	}
	for i := range in.ObjectMeta.OwnerReferences {
		a := &in.ObjectMeta.OwnerReferences[i]
		if a.Controller != nil {
		}
	}
	if in.ObjectMeta.Initializers != nil {
		for i := range in.ObjectMeta.Initializers.Pending {
			a := &in.ObjectMeta.Initializers.Pending[i]
		}
		if in.ObjectMeta.Initializers.Result != nil {
			if in.ObjectMeta.Initializers.Result.Details != nil {
				for i := range in.ObjectMeta.Initializers.Result.Details.Causes {
					a := &in.ObjectMeta.Initializers.Result.Details.Causes[i]
				}
			}
		}
	}
	for i := range in.ObjectMeta.Finalizers {
		a := &in.ObjectMeta.Finalizers[i]
	}
	if in.Spec.Parallelism != nil {
	}
	if in.Spec.Selector != nil {
		for i := range in.Spec.Selector.MatchExpressions {
			a := &in.Spec.Selector.MatchExpressions[i]
		}
	}
	api_v1.SetDefaults_PodSpec(&in.Spec.Template.Spec)
	for i := range in.Spec.Template.Spec.Volumes {
		a := &in.Spec.Template.Spec.Volumes[i]
		api_v1.SetDefaults_Volume(a)
		if a.VolumeSource.HostPath != nil {
		}
		if a.VolumeSource.EmptyDir != nil {
			if a.VolumeSource.EmptyDir.SizeLimit.d.Dec != nil {
			}
		}
		if a.VolumeSource.GCEPersistentDisk != nil {
		}
		if a.VolumeSource.AWSElasticBlockStore != nil {
		}
		if a.VolumeSource.GitRepo != nil {
		}
		if a.VolumeSource.Secret != nil {
			api_v1.SetDefaults_SecretVolumeSource(a.VolumeSource.Secret)
			for j := range a.VolumeSource.Secret.Items {
				b := &a.VolumeSource.Secret.Items[j]
			}
		}
		if a.VolumeSource.NFS != nil {
		}
		if a.VolumeSource.ISCSI != nil {
			api_v1.SetDefaults_ISCSIVolumeSource(a.VolumeSource.ISCSI)
			if a.VolumeSource.ISCSI.SecretRef != nil {
			}
		}
		if a.VolumeSource.Glusterfs != nil {
		}
		if a.VolumeSource.PersistentVolumeClaim != nil {
		}
		if a.VolumeSource.RBD != nil {
			api_v1.SetDefaults_RBDVolumeSource(a.VolumeSource.RBD)
		}
		if a.VolumeSource.FlexVolume != nil {
		}
		if a.VolumeSource.Cinder != nil {
		}
		if a.VolumeSource.CephFS != nil {
		}
		if a.VolumeSource.Flocker != nil {
		}
		if a.VolumeSource.DownwardAPI != nil {
			api_v1.SetDefaults_DownwardAPIVolumeSource(a.VolumeSource.DownwardAPI)
			for j := range a.VolumeSource.DownwardAPI.Items {
				b := &a.VolumeSource.DownwardAPI.Items[j]
				if b.FieldRef != nil {
					api_v1.SetDefaults_ObjectFieldSelector(b.FieldRef)
				}
				if b.ResourceFieldRef != nil {
				}
			}
		}
		if a.VolumeSource.FC != nil {
		}
		if a.VolumeSource.AzureFile != nil {
		}
		if a.VolumeSource.ConfigMap != nil {
			api_v1.SetDefaults_ConfigMapVolumeSource(a.VolumeSource.ConfigMap)
		}
		if a.VolumeSource.VsphereVolume != nil {
		}
		if a.VolumeSource.Quobyte != nil {
		}
		if a.VolumeSource.AzureDisk != nil {
			api_v1.SetDefaults_AzureDiskVolumeSource(a.VolumeSource.AzureDisk)
			if a.VolumeSource.AzureDisk.CachingMode != nil {
			}
			if a.VolumeSource.AzureDisk.FSType != nil {
			}
			if a.VolumeSource.AzureDisk.Kind != nil {
			}
		}
		if a.VolumeSource.PhotonPersistentDisk != nil {
		}
		if a.VolumeSource.Projected != nil {
			api_v1.SetDefaults_ProjectedVolumeSource(a.VolumeSource.Projected)
			for j := range a.VolumeSource.Projected.Sources {
				b := &a.VolumeSource.Projected.Sources[j]
				if b.Secret != nil {
				}
				if b.DownwardAPI != nil {
				}
				if b.ConfigMap != nil {
				}
			}
		}
		if a.VolumeSource.PortworxVolume != nil {
		}
		if a.VolumeSource.ScaleIO != nil {
			api_v1.SetDefaults_ScaleIOVolumeSource(a.VolumeSource.ScaleIO)
		}
	}
	for i := range in.Spec.Template.Spec.InitContainers {
		a := &in.Spec.Template.Spec.InitContainers[i]
		api_v1.SetDefaults_Container(a)
		for j := range a.Ports {
			b := &a.Ports[j]
			api_v1.SetDefaults_ContainerPort(b)
		}
		for j := range a.EnvFrom {
			b := &a.EnvFrom[j]
			if b.ConfigMapRef != nil {
			}
			if b.SecretRef != nil {
			}
		}
		for j := range a.Env {
			b := &a.Env[j]
			if b.ValueFrom != nil {
				if b.ValueFrom.ConfigMapKeyRef != nil {
				}
				if b.ValueFrom.SecretKeyRef != nil {
				}
			}
		}
		api_v1.SetDefaults_ResourceList(&a.Resources.Limits)
		api_v1.SetDefaults_ResourceList(&a.Resources.Requests)
		for j := range a.VolumeMounts {
			b := &a.VolumeMounts[j]
		}
		if a.LivenessProbe != nil {
			api_v1.SetDefaults_Probe(a.LivenessProbe)
			if a.LivenessProbe.Handler.Exec != nil {
			}
			if a.LivenessProbe.Handler.HTTPGet != nil {
				api_v1.SetDefaults_HTTPGetAction(a.LivenessProbe.Handler.HTTPGet)
				for j := range a.LivenessProbe.Handler.HTTPGet.HTTPHeaders {
					b := &a.LivenessProbe.Handler.HTTPGet.HTTPHeaders[j]
				}
			}
			if a.LivenessProbe.Handler.TCPSocket != nil {
			}
		}
		if a.Lifecycle != nil {
			if a.Lifecycle.PostStart != nil {
			}
		}
		if a.SecurityContext != nil {
			if a.SecurityContext.Capabilities != nil {
				for j := range a.SecurityContext.Capabilities.Add {
					b := &a.SecurityContext.Capabilities.Add[j]
				}
			}
			if a.SecurityContext.SELinuxOptions != nil {
			}
			if a.SecurityContext.RunAsUser != nil {
			}
		}
	}
	if in.Spec.Template.Spec.SecurityContext != nil {
		for i := range in.Spec.Template.Spec.SecurityContext.SupplementalGroups {
			a := &in.Spec.Template.Spec.SecurityContext.SupplementalGroups[i]
		}
		if in.Spec.Template.Spec.SecurityContext.FSGroup != nil {
		}
	}
	for i := range in.Spec.Template.Spec.ImagePullSecrets {
		a := &in.Spec.Template.Spec.ImagePullSecrets[i]
	}
	if in.Spec.Template.Spec.Affinity != nil {
		if in.Spec.Template.Spec.Affinity.NodeAffinity != nil {
			if in.Spec.Template.Spec.Affinity.NodeAffinity.RequiredDuringSchedulingIgnoredDuringExecution != nil {
				for i := range in.Spec.Template.Spec.Affinity.NodeAffinity.RequiredDuringSchedulingIgnoredDuringExecution.NodeSelectorTerms {
					a := &in.Spec.Template.Spec.Affinity.NodeAffinity.RequiredDuringSchedulingIgnoredDuringExecution.NodeSelectorTerms[i]
					for j := range a.MatchExpressions {
						b := &a.MatchExpressions[j]
					}
				}
			}
			for i := range in.Spec.Template.Spec.Affinity.NodeAffinity.PreferredDuringSchedulingIgnoredDuringExecution {
				a := &in.Spec.Template.Spec.Affinity.NodeAffinity.PreferredDuringSchedulingIgnoredDuringExecution[i]
			}
		}
		if in.Spec.Template.Spec.Affinity.PodAffinity != nil {
			for i := range in.Spec.Template.Spec.Affinity.PodAffinity.RequiredDuringSchedulingIgnoredDuringExecution {
				a := &in.Spec.Template.Spec.Affinity.PodAffinity.RequiredDuringSchedulingIgnoredDuringExecution[i]
			}
			for i := range in.Spec.Template.Spec.Affinity.PodAffinity.PreferredDuringSchedulingIgnoredDuringExecution {
				a := &in.Spec.Template.Spec.Affinity.PodAffinity.PreferredDuringSchedulingIgnoredDuringExecution[i]
			}
		}
		if in.Spec.Template.Spec.Affinity.PodAntiAffinity != nil {
		}
	}
	for i := range in.Spec.Template.Spec.Tolerations {
		a := &in.Spec.Template.Spec.Tolerations[i]
	}
	for i := range in.Spec.Template.Spec.HostAliases {
		a := &in.Spec.Template.Spec.HostAliases[i]
	}
	for i := range in.Status.Conditions {
		a := &in.Status.Conditions[i]
	}
}

func SetObjectDefaults_JobList(in *JobList) {
	for i := range in.Items {
		a := &in.Items[i]
		SetObjectDefaults_Job(a)
	}
}
